import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {

  let age = 19
  let inStock = true

  let arr = ["ironman","spider man","wanda","captain"]
  let alpha = <p>hello how are {2+2} you</p>
  
  return (
    <>
      {/* <h1 style={{
      backgroundColor:"lightgreen",
      "color":"blue",
      boxShadow:"1px 1px 5px 15px lightblue",
      borderRadius:"5px",
      padding:"0.5rem",
      textAlign:"center",
      maxWidth:"1280px"
    }}>i am MBGA</h1> */}

    /* {age > 18 ? <p style={{color:"Green", fontSize:"40px"}}>You can drive</p> : <p style={{color:"red", fontSize:"40px"}}>You cannot drive</p> }
    {inStock && <p>Product is out of stock</p>}
    {inStock || <p>Product is out of stock</p>} */

    /* {arr.map((item,index)=>{
      return <h1 >{item}</h1>
    })} */

    {React.createElement("h1",null,"hello this is create element")}

    {/* with props */}
    {React.createElement("h1",{className:"head" , style: {color:"red"} },"hello from these")}

    {/* {React.createElement(
      "h1",
      null,
      "my name is" , alpha
    )} */}
      
    /* {
      React.createElement(
        "h1",
        null,
        React.createElement(
          "p",
          {style:{backgroundColor:"red"}},
          "hello1"
        ),
        React.createElement(
          "p",
          {style:{backgroundColor:"red"}},
          "hello2"
        ),
        React.createElement(
          "p",
          {style:{backgroundColor:"red"}},
          "hello3"
        ),
        React.createElement(
          "p",
          {style:{backgroundColor:"red"}},
          "hello4"
        )
      )
    } */


    {
      React.createElement(
        "div",
        {className:"card"},
        React.createElement(
          "h1",
          null,
          `hello ${user.names}`
        ),
        React.createElement(
          "p",
          null,
          `You are ${user.age + 1} years old next year.`
        )
      )
    }
      
      
    {/* <h1>helloww  jsx </h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, voluptas. 
    Temporibus accusantium quam sapiente voluptatibus impedit. Quam maiores, velit possimus esse pariatur rem eligendi cupiditate adipisci voluptas, enim exercitationem architecto!
    A, consequuntur cum impedit quam numquam expedita quisquam in incidunt dolorem sunt necessitatibus tempore suscipit dolor cumque laudantium harum perspiciatis accusantium voluptas officiis pariatur modi? Ullam sunt ea maxime deleniti?
    Fugiat nostrum, nulla placeat sequi soluta pariatur consequatur </p> */}
    </>
  )
}

export default App


// what is jsx ??
// JSX is a sytex extension for javascript used in react.
// it lets you write HTMl like code inside javascript

// React code heavily uses JSX, a syntax extension that looks like HTML but is not standard JavaScript; 
// Babel converts this into standard JavaScript function calls usable by browsers.

// JSX Transpilation: Converts JSX into JavaScript function calls.
// ES6+ to ES5: Converts modern JavaScript to ES5 for wider browser compatibility

// Embedding expressions 

// Valid Expressions:

// Variables
// Function calls
// Ternary expressions
// Mathematical operations


// statement like if-else,for etc. are not allowed

// Note:
// JSX and template literals both folllow this rule:
// only expressions can go inside {} or ${} and not statements 

// Expressions can be part of statements (e.g., in conditions or assignments), 
// but statements cannot be used where a value is expected, such as function arguments.
// While expressions always produce a value, statements focus on actions like variable declaration 
// or loops, and may include expressions within them.
// In contexts like React JSX, expressions are used for embedding values or conditional rendering, 
// whereas statements like if-else require alternative approaches.


// In React, keys are special string attributes you assign to elements in a list 
// (like those generated by the map() function in JSX) to give each item a 
// stable, unique identity, helping React efficiently track which items have changed, been added, or removed during re-renders. 
// This optimizes performance by allowing React to update only the necessary parts of the DOM instead of re-rendering the entire list,
//  which can prevent issues like lost component state or inefficient updates.


// Why Keys Are Necessary
// When you use map() to render an array of JSX elements (e.g., a list of <li> items), React needs a way to differentiate between them across renders. 
// Without keys, React defaults to using the item's index in the array, which can lead to problems if the list order changes 
// (due to sorting, insertions, or deletions), causing bugs like mismatched state or unnecessary re-renders. For example:

// If you delete an item from the start of a list without keys, 
// React might incorrectly shift states or props to the wrong elements.

// Keys enable React's reconciliation algorithm to make precise DOM updates, improving speed and reliability.


// React behind the scenes
// compled to react.createElement() behind the scenes
// (JSX)      const element = <h1>Hello,school4U</h1>;
// (Complied) const element = React.createElement("h1",null,"Hello School4U");
//                              React.createElement(type,props,....children)              
